//
// Created by dima on 02/12/17.
//

#ifndef TCP_SHMAFKA_MSGCONSTS_H
#define TCP_SHMAFKA_MSGCONSTS_H

#define CONSTS_MSG_TYPE_OFFSET 0
#define CONSTS_MSG_TYPE_LEN 4

#define CONSTS_POST_CHANEL_OFFSET (CONSTS_MSG_TYPE_OFFSET + CONSTS_MSG_TYPE_LEN)
#define CONSTS_POST_CHANEL_LEN 16

#define CONSTS_POST_MSG_CHUNK_OFFSET  (CONSTS_POST_CHANEL_OFFSET + CONSTS_POST_CHANEL_LEN)
#define CONSTS_POST_MSG_CHUNK_LEN 4

#define CONSTS_POST_MSG_NUM_OF_CHUNKS_OFFSET (CONSTS_POST_MSG_CHUNK_OFFSET + CONSTS_POST_MSG_CHUNK_LEN)
#define CONSTS_POST_MSG_NUM_OF_CHUNKS_LEN 4
#define CONSTS_POST_MSG_DATA_OFFSTE (CONSTS_POST_MSG_NUM_OF_CHUNKS_OFFSET + CONSTS_POST_MSG_NUM_OF_CHUNKS_LEN)

#define CONSTS_REGISTER_CHANEL_OFFSET (CONSTS_MSG_TYPE_OFFSET + CONSTS_MSG_TYPE_LEN)
#define CONSTS_REGISTER_CHANEL_LEN 16

#define CONSTS_DEREGISTER_CHANEL_OFFSET (CONSTS_MSG_TYPE_OFFSET + CONSTS_MSG_TYPE_LEN)
#define CONSTS_DEREGISTER_CHANEL_LEN 16


#endif //TCP_SHMAFKA_MSGCONSTS_H
